const useAboutUsContent = () => {

    const content = {
        who_we_are: "Our company ANAJWALA is all about delivering fresh essentials right to your doorstep, founded In 1995 By One Of The Well Known Personality In Hospitality Industry , Mr. Nikhilesh Pandey He Has Invested More Than 30 Years In Well Known Brand . Finest In Quality This Appetizing Brand Was Brought In The Year 2023 (The Cleanest City Of India) By Mr. Nikhilesh Pandey ( More Than 30 Years Of Experience , Hotel Management ) & Mr. Harsh Pandey (MBA In Marketing And Finance). We believe that the foundation of great cooking starts with the best ingredients. That's why we are committed to providing our customers with all the essentials (Grocery ) that not only meets but exceeds your expectations. Our brand Anajwala, is a pioneer brand of grains made to provide quality and nutritious grain flour to the nation. Due to the time crunch in today's fast paced world, vision like that of our brand is needed. This idea not only meets the basic nutritional needs of consumers but also wipes out regular time consuming visits to grain store. This innovative idea promotes ‘hyper fresh concept’ as it promises to deliver the desired flour within 24 hours. Varieties of fresh flour like wheat flour and multi grain are provided. We also plan to add more varieties of flour in the future. To cater to the needs of diverse classes our wheat flour has 3 different types (based on quality) which are - 'Silver' 'Gold' and 'Platinum' Eradicating adulteration from the food is the need of the hour as many diseases sprout from the adulterants. Addition of dyes such as sudan dyes for coloring or melamine for increasing protein content can pose big risks to human health. A section of consumers aware of the adulteration in flour switched to the packaged food and as observed from the research studies, preservatives present in packaged food is one of the causes of cancer. Our brand fulfills the preservative free flour requirement of the consumers. Anajwala also realises its social responsibility towards society and in order to fulfill a social duty, we take up the initiative to reconnect the abandoned people with society by making them a part of our business. Their participation in advertising and propagating our concept among masses would ensure their economic self reliance. It would supply them with a purpose, dignity and confidence to tackle challenges head-on thrown at them by life.",
        our_commitment : "At the heart of our brand lies a commitment to excellence, health, and customer happiness. We take pride in offering top-quality wheat flour that embodies the essence of purity and taste. Our values revolve around ensuring the highest standards of quality, promoting health-conscious choices, and guaranteeing satisfaction with every purchase.  Our mission is to be more than just a wheat flour provider; we aspire to be your culinary partner in creating memorable meals. By offering a product that is not only nutritious but also delicious, we aim to elevate your cooking experience and bring a touch of joy to your kitchen. Trust us to be the cornerstone of your culinary adventures, providing you with fresh, versatile wheat flour that adds a touch of goodness to every dish.",
        range_of_flours : "At Anajwala, we offer a diverse range of flour varieties, including whole wheat, rice, millet, and specialty flours, all sourced from trusted local farmers. We take pride in our meticulous milling process, ensuring that each batch retains its nutrients and flavor. Say goodbye to stale, store-bought flour and hello to the rich taste and health benefits of fresh flour!",
        quality_assurance : "Quality is at the heart of everything we do. Our team of experts carefully selects the finest grains, which are then milled using traditional methods that preserve their natural goodness. We prioritize sustainability and ethical sourcing, ensuring that our practices support local agriculture and contribute to a healthier planet.",
        your_satisfaction_our_priority : "At Anajwala, we offer a hassle-free delivery service, bringing fresh flour straight to your home. Our user-friendly online platform makes it easy to place orders and choose from our range of products. Plus, our customer support team is always ready to assist you with any questions or concerns. Your satisfaction is our top priority, and we strive to exceed your expectations with every purchase.",
    }

    return content
}

export {
    useAboutUsContent
}